### ISSUE TITLE
Add Proper Documentation on how to use the console version of zomato_client.

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Zomato-Client#2]
Changes Required : 
- Documentation of the console version
- Need to add a README.md file in example folder to be shown on pub.dev package site.

**Comment by infiniteoverflow** [comment]
@graphicbeacon Will you be able to work on this part ?

**Comment by graphicbeacon** [comment]
> @graphicbeacon Will you be able to work on this part ?

@infiniteoverflow Sure, I'll sort that out
