### ISSUE TITLE
Missing the Search feature

### ISSUE THREAD

**Issue by Skquark** [infiniteoverflow/Zomato-Client#3]
I've been playing with implementing a local restaurants listing, and was easy enough to figure out the basics of the API.  However, when I got to the important part of getting a list of restaurants in a specific category within a radius of my lat/long, I couldn't find the method for calling zomato.search or zomato.getRestaurants, which I expected to be in there somehow.  Maybe I'm missing the trick, or it just hasn't been implemented yet, but I see it in https://developers.zomato.com/documentation#!/restaurant/search API.
Thanks, looking forward to playing with the results and seeing what I can do with it in my app..

**Comment by infiniteoverflow** [comment]
Yes , thanks a lot for pointing it out. We kind of missed that API , we will be working on it to resolve this.

**Comment by Skquark** [comment]
Cool, understandable.. While we're looking at the API ref, I also noticed it's missing calls for getRestaurant and getReviews, which you give the res_id from the search.  Looks easy enough to add and use, then I can start building my own interface around it.  Thanks,.

**Comment by infiniteoverflow** [comment]
Thanks a lot for mentioning this. Deeply regret the late response.
We will be working on this issue by end of the month due to some other engagements. We will be looking forward to hearing from you on your experience building the interface.
